name = "FluxModels"
uuid = "5a58f058-f5b9-4204-9644-e62f3e70829d"
authors = ["Kyle Daruwalla"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Flux = "0.10, 0.11"
Reexport = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
